### ISSUE TITLE
 Connection pool problem between ASP.NET and SQL Server

### ISSUE THREAD

**Issue by ungureanuraluca15** [ehm2097/web-sql#5]
It seems that at some certain periods of time, it throws an exception : "Timeout expired. The timeout period elapsed prior to obtaining a connection from the pool. This may have occurred because all pooled connections were in use and max pool size was reached" .

**Comment by ehm2097** [comment]
Issue confirmed. Cause seems to be an incorrect assumption about how connection pooling works in .Net. Fix in progress

**Comment by ehm2097** [comment]
Fixed in v1.1.2
